### ISSUE TITLE
How can this help in cases with duplicate definitions?

### ISSUE THREAD

**Issue by benlesh** [hax/proposal-class-brand-check#2]
With the libraries that I work on, given that they are used heavily in node, I've learned that I can't always rely on `instanceof` checks, because sometimes you get an instance that came from another copy of the same module. This leads to a LOT of developer confusion. This means that it's more prudent to use duck-type checks. The private-in proposal might be a promising way to solve this, or it might not handle that problem. 

How could this proposal help with this common issue?

**Comment by ljharb** [comment]
Neither proposal will handle that. That’s only possibly to solve if a class is designed to Interoperate with duplicates of itself (the same version, or different ones).

**Comment by hax** [comment]
Yes, as Jordan said, both proposals can not deal with cross-realms or duplicate module instances cases. Personally I hope module block and shared realm proposal could help to solve some of such cases.

Note, because `#x in o` looks very like duck type check, it could give the wrong impression to programmers. This is one of the reasons why I feel duck type style is not a good choice for brand check.

**Comment by ljharb** [comment]
@hax which impression? The only impression I'd expect is "the object has the field", which is the precise and only thing the proposal is intended to answer.

**Comment by hax** [comment]
@ljharb The impression like this issue: "The private-in proposal might be a promising way to solve this" (because private-in looks like duck type check".

**Comment by ljharb** [comment]
right but what is "this"? There are plenty of problems where that *is* the best way to solve it. Duck-type checks are a good thing, and are a massively idiomatic part of the language, and while there's some cases where they aren't ideal, there's plenty where they are.

**Comment by hax** [comment]
@ljharb I believe "this" in that sentence ("The private-in proposal might be a promising way to solve *this*") means "duplicate definitions".

> Duck-type checks are a good thing, and are a massively idiomatic part of the language

I agree that. But `#x in o` is not really duck type checks, it just look like duck type check and do not share the same merits of real duck type check.

**Comment by ljharb** [comment]
That the OP's issue isn't addressed by either proposal isn't really relevant to either proposal.

It absolutely is a duck-type check - it's asking "does this field exist? i don't care what you are as long as you have the field" - and that's exactly what the code that follows it will care about when it's only accessing that field on the object.

**Comment by hax** [comment]
Yes either proposals don't address that issue, but it is relevant in a weird form: the author of this issue think "the private-in proposal might be a promising way to solve this" because private-in looks like duck type check (or in your opinion it's just duck type check) and people think duck type check should and could address that issue.

**Comment by ljharb** [comment]
People think all kinds of things about all kinds of proposals - the OP also said "or might not", so I don't think there's the confusion factor you're implying there is.

**Comment by hax** [comment]
I think this issue has been answered, so I close it. Feel free to reopen it if there is any new information to discuss.
